### ISSUE TITLE
Firefox Extension

### ISSUE THREAD

**Issue by AndyTheFactory** [ZohebAbai/Colab_Auto_Reconnect#1]
Hello!

Great Extension! 

I have been using it in Chrome sucessfully, works very well.
Somehow the Firefox extension does not seem to do anything. It installs all-right, but in the console the "reconnecting" does not appear, and the Extension Icon is missing in the toolbar. 
There was no error installing it

I tested it in Firefox 85.0b5 (64-bit)
![firefox_hWfJED5RBk](https://user-images.githubusercontent.com/863810/105576848-4d5af080-5d7e-11eb-8096-3544b698db5d.jpg)

Thanks so much for this great extension!

**Comment by ZohebAbai** [comment]
Hi @AndyTheFactory,
 
Apologies for replying so late.
Thanks for the nice feedback. I am glad the extension helped. 
It was basically built as a chrome extension. Later I tried to replicate it for firefox too by tweaking few elements of code.
I will try to fix it and update it within few days.
Thanks.

**Comment by AndyTheFactory** [comment]
could it be because the "incognito=split" is no longer supported in Firefox ?

see browser compatibility [here ](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/incognito)

i tried this out with **web-ext run** and it did appear in firefox after I removed that line

**Comment by ZohebAbai** [comment]
While tweaking the codes for firefox I had changed it to "spanning". 
Thanks anyway, to bring this up. It has been fixed and updated.
